@startuml usecase
left to right direction

actor ゲストユーザー as guest
actor ログインユーザー as loginUser
actor Cron as c << System >>

package "SNS System" as sns{
    (ログインする) as login
    (トレンドの投稿を閲覧する) as lookTrend
    (フォロワーの投稿を閲覧する) as lookFollower
    (プロフィールを作成する) as profile
    (ユーザーをフォローする) as follow
    (ユーザーをアンフォローする) as unfollow
    (投稿を作成する) as post
    (投稿をスケジュールする) as schedule
    (投稿を削除する) as delete
    (投稿にいいねをする) as good
    (投稿にしたいいねを取り消す) as ungood
    (投稿に返信をする) as reply
    (プライベートメッセージを送る) as private
    (通知を見る) as notification
}

guest --> lookTrend
guest --> loginUser
loginUser --> sns

schedule --> c

@enduml