@startuml profile

actor ユーザー as u
participant ブラウザ as b
participant サーバー as s
database DB as d

u --> b: プロフィール入力
b --> s: POSTリクエスト
s --> s: セッション情報を確認
s --> s: ユーザー入力の検証
s --> d: ユーザーのプロフィール情報を更新
d --> s: 更新成功
s --> b: プロフィールページをレンダリング
b --> u: プロフィールを表示


@enduml