@startuml register

actor ゲスト as g
participant ブラウザ as b
participant サーバー as s
database DB as d

g --> b: メルアドとパスワードを入力
b --> s: POSTリクエスト
s --> s: ユーザー入力の検証
s --> d: 同一アドレスがないか確認
d --> s: 同一アドレスがない結果を返す
s --> d: ユーザーデータを保存
s --> s: 署名付きURLを作成
s --> g: 検証用メールを送信
s --> b: 「検証用メールを送信しました」の表示
g --> b: 検証用メールから署名付きURLを開く
b --> s: 検証用メールのGETリクエスト
s --> s: 署名の認証
s --> b: 認証の成功
b --> g: 認証成功の表示


@enduml