@startuml er

Entity users{
    + id: INT [PK]
    --
    username: String
    account_name: String
    password: String
    email: String
    email_verified: bool
    created_at: Datetime
    updated_at: Datetime
}

Entity profile{
    + id: INT [PK]
    --
    # user_id: INT [FK]
    age: INT
    location: String
    description: String
    profile_image_path: String
    created_at: Datetime
    updated_at: Datetime
}

Entity posts{
    + id: INT [PK]
    --
    # user_id: INT [FK]
    content: String
    url: String
    media_path: String
    scheduled_at: Datetime
    created_at: Datetime
    updated_at: Datetime
}

Entity comments{
    + id: INT [PK]
    --
    # user_id: INT [FK]
    # post_id: INT [FK]
    # parent_comment_id: INT [FK]
    content: String
    url: String
    media_path: String
    created_at: Datetime
}

Entity post_likes{
    + user_id: INT [PK-FK]
    + post_id: INT [PK-FK]
    --
    created_at: Datetime
}

Entity comment_likes{
    + user_id: INT [PK-FK]
    + comment_id: INT [PK-FK]
    --
    created_at: Datetime
}

Entity notifications{
    + id: INT [PK]
    --
    # user_id: INT [FK]
    # related_at: INT: [FK]
    notification_type: String
    content: String
    is_read: bool
    created_at: Datetime
}

Entity follows{
    + following_user_id: INT [PK-FK]
    + follower_user_id: INT [PK-FK]
    --
    created_at: Datetime
}

Entity dm_threads{
    + id: INT [PK]
    --
    # user_id1: INT [FK]
    # user_id2: INT [FK]
    url: String
}

Entity private_messages{
    + id: INT [PK]
    --
    # private_room_id: INT [FK]
    # sender_user_id: INT [FK]
    # receiver_user_id: INT [FK]
    message: String
    media_path: String
    created_at: Datetime
}

Entity post_like_notifications{
    + id: INT [PK]
    --
    # user_id: INT [FK]
    # post_id: INT [FK]
    is_read: INT
    created_at: Datetime
}


users ||--o{ posts: writes
users ||--o{ comments: comments
posts ||--o{ comments: has
posts ||--o{ post_likes: has
comments ||--o{ comment_likes: has
comments ||--o{ comments: has
users ||--o{ follows: following
users ||--o{ follows: be followed
users ||--o{ notifications: notices
users ||--o{ post_likes: likes
users ||--o{ comment_likes: likes
users ||--|| profile: has
users }|--o{ dm_threads: has
dm_threads ||--o{ private_messages: belongs to 

@enduml